import { v } from 'convex/values'
import { internal } from './_generated/api'
import type { Doc, Id } from './_generated/dataModel'
import { internalAction, internalMutation, mutation, query, type MutationCtx, type QueryCtx } from './_generated/server'
import { hasLearnV2Access, requireLearnV2MutationAccess, requireLearnV2QueryAccess } from './lib/learnV2Access'
import { validateLearnV2SessionContentCandidate } from '../shared/learn-v2-session-content'

const TYPE = 'session_content_generation'
const LEASE_MS = 5 * 60_000
const MAX_ATTEMPTS = 2

async function block(ctx: MutationCtx, job: Doc<'learnJobs'>, reason: string) { await ctx.db.patch(job._id, { status: 'blocked', terminalReason: reason, revision: job.revision + 1, leaseToken: undefined, leaseExpiresAt: undefined, checkpoint: undefined, updatedAt: Date.now() }) }

async function inputs(ctx: MutationCtx | QueryCtx, userId: string, job: Doc<'learnJobs'>) {
  if (!job.studySessionId || !job.studyPlanRevisionId || !job.blueprintRevisionId) throw new Error('Session-content job is incomplete')
  const session = await ctx.db.get(job.studySessionId); const plan = await ctx.db.get(job.studyPlanRevisionId); const blueprint = await ctx.db.get(job.blueprintRevisionId)
  if (!session || !plan || !blueprint || session.userId !== userId || plan.userId !== userId || blueprint.userId !== userId || session.studyPlanRevisionId !== plan._id || session.status !== 'planned' || session.revision !== job.expectedSessionRevision || plan.status !== 'accepted' || plan.blueprintRevisionId !== blueprint._id || blueprint.status !== 'accepted' || blueprint.recordRevision !== job.expectedBlueprintRecordRevision) throw new Error('input_revision_conflict')
  const latest = await ctx.db.query('studyPlanRevisions').withIndex('by_userId_and_studyPlanId_and_revision', q => q.eq('userId', userId).eq('studyPlanId', plan.studyPlanId)).order('desc').first()
  const stable = await ctx.db.get(plan.studyPlanId)
  if (!latest || latest._id !== plan._id || stable?.activeRevisionId !== plan._id) throw new Error('input_revision_conflict')
  const retrieval = await ctx.db.query('studySessionRetrievalObjectives').withIndex('by_userId_and_studySessionId_and_order', q => q.eq('userId', userId).eq('studySessionId', session._id)).take(16)
  return { session, plan, blueprint, retrieval }
}

export const leaseSessionContentGeneration = internalMutation({ args: { tokenIdentifier: v.string(), jobId: v.id('learnJobs'), expectedRevision: v.number() }, handler: async (ctx, args) => {
  const job = await ctx.db.get(args.jobId); if (!job || job.userId !== args.tokenIdentifier || job.type !== TYPE || job.revision !== args.expectedRevision) throw new Error('Session-content job not found')
  if (!(await hasLearnV2Access(ctx, args.tokenIdentifier))) { await block(ctx, job, 'access_revoked'); return { kind: 'blocked' as const } }
  try { await inputs(ctx, args.tokenIdentifier, job) } catch { await block(ctx, job, 'input_revision_conflict'); return { kind: 'blocked' as const } }
  if (job.status === 'running' && (job.leaseExpiresAt ?? 0) <= Date.now()) { await block(ctx, job, 'provider_outcome_unknown'); return { kind: 'blocked' as const } }
  if (job.status !== 'queued' && !(job.status === 'leased' && (job.leaseExpiresAt ?? 0) <= Date.now())) throw new Error('Session-content job is not leaseable')
  if ((job.attempts ?? 0) >= MAX_ATTEMPTS) { await ctx.db.patch(job._id, { status: 'failed', terminalReason: 'attempt_limit_exhausted', revision: job.revision + 1, updatedAt: Date.now() }); return { kind: 'blocked' as const } }
  const leaseToken = crypto.randomUUID(); const revision = job.revision + 1
  await ctx.db.patch(job._id, { status: 'leased', attempts: (job.attempts ?? 0) + 1, leaseToken, leaseExpiresAt: Date.now() + LEASE_MS, revision, updatedAt: Date.now() })
  return { kind: 'leased' as const, leaseToken, revision }
} })

export const beginSessionContentGeneration = internalMutation({ args: { tokenIdentifier: v.string(), jobId: v.id('learnJobs'), leaseToken: v.string(), expectedRevision: v.number() }, handler: async (ctx, args) => {
  const job = await ctx.db.get(args.jobId); if (!job || job.userId !== args.tokenIdentifier || job.type !== TYPE || job.status !== 'leased' || job.leaseToken !== args.leaseToken || job.revision !== args.expectedRevision || (job.leaseExpiresAt ?? 0) <= Date.now()) throw new Error('Session-content lease unavailable')
  try { await inputs(ctx, args.tokenIdentifier, job) } catch { await block(ctx, job, 'input_revision_conflict'); return { status: 'blocked' as const, revision: job.revision + 1 } }
  await ctx.db.patch(job._id, { status: 'running', checkpoint: 'preparing_input', revision: job.revision + 1, updatedAt: Date.now() }); return { status: 'running' as const, revision: job.revision + 1 }
} })

export const commitSessionContentCandidate = internalMutation({ args: { tokenIdentifier: v.string(), jobId: v.id('learnJobs'), leaseToken: v.string(), expectedRevision: v.number(), candidateJson: v.string() }, handler: async (ctx, args) => {
  const job = await ctx.db.get(args.jobId); if (!job || job.userId !== args.tokenIdentifier || job.type !== TYPE || job.status !== 'running' || job.leaseToken !== args.leaseToken || job.revision !== args.expectedRevision || (job.leaseExpiresAt ?? 0) <= Date.now()) throw new Error('Session-content lease unavailable')
  let candidate: ReturnType<typeof validateLearnV2SessionContentCandidate>; try { candidate = validateLearnV2SessionContentCandidate(JSON.parse(args.candidateJson), (job.dispatchSupportingSourceSnapshotIds ?? []).map(String)) } catch { const session = job.studySessionId ? await ctx.db.get(job.studySessionId) : null; if (session?.status === 'planned') await ctx.db.patch(session._id, { status: 'generation_failed', revision: session.revision + 1, auditReasonCode: 'candidate_validation_failed' }); await ctx.db.patch(job._id, { status: 'failed', terminalReason: 'candidate_validation_failed', revision: job.revision + 1, leaseToken: undefined, leaseExpiresAt: undefined, checkpoint: undefined, updatedAt: Date.now() }); return { status: 'generation_failed' as const } }
  let input: Awaited<ReturnType<typeof inputs>>; try { input = await inputs(ctx, args.tokenIdentifier, job) } catch { await block(ctx, job, 'input_revision_conflict'); return { status: 'blocked' as const } }
  const sourceToExcerpt = new Map<string, Id<'learnSourceExcerpts'>>()
  for (const sourceId of job.dispatchSupportingSourceSnapshotIds ?? []) { const source = await ctx.db.get(sourceId); if (!source || source.userId !== args.tokenIdentifier || source.status !== 'user_accepted' || (source.effectiveStatus && source.effectiveStatus !== 'user_accepted') || source.rightsStatus !== 'permitted' || source.conflictStatus !== 'clear' || source.evidencePurgedAt !== undefined) { await block(ctx, job, 'evidence_unavailable'); return { status: 'blocked' as const } }; const excerpt = await ctx.db.query('learnSourceExcerpts').withIndex('by_userId_and_sourceSnapshotId_and_evidencePurgedAt', q => q.eq('userId', args.tokenIdentifier).eq('sourceSnapshotId', source._id).eq('evidencePurgedAt', undefined)).first(); if (!excerpt || excerpt.rightsStatus !== 'permitted' || !excerpt.excerpt) { await block(ctx, job, 'evidence_unavailable'); return { status: 'blocked' as const } }; sourceToExcerpt.set(String(source._id), excerpt._id) }
  const existing = await ctx.db.query('sessionContent').withIndex('by_userId_and_studySessionId_and_revision', q => q.eq('userId', args.tokenIdentifier).eq('studySessionId', input.session._id)).take(2); if (existing.length) throw new Error('Session content revision already exists')
  const now = Date.now(); const contentId = await ctx.db.insert('sessionContent', { userId: args.tokenIdentifier, studySessionId: input.session._id, revision: 1, status: 'published', assessmentRubricSnapshot: JSON.stringify(candidate.assessmentRubric), generatorVersion: candidate.generatorVersion, createdAt: now, publishedAt: now })
  const objective = await ctx.db.get(input.session.primaryObjectiveId)
  if (!objective || objective.assessmentContract === undefined || JSON.stringify(candidate.assessmentRubric) !== JSON.stringify(objective.assessmentContract)) { await ctx.db.delete(contentId); await block(ctx, job, 'rubric_revision_conflict'); return { status: 'blocked' as const } }
  for (const item of candidate.blocks) await ctx.db.insert('sessionContentBlocks', { userId: args.tokenIdentifier, sessionContentId: contentId, order: item.order, kind: item.kind, content: item.content, claimOrdersJson: JSON.stringify(item.claimOrders) })
  for (const item of candidate.claims) { const claimId = await ctx.db.insert('sessionContentClaims', { userId: args.tokenIdentifier, sessionContentId: contentId, order: item.order, claim: item.claim, verifierVersion: item.verifierVersion, confidence: item.confidence }); for (const sourceId of item.supportSourceSnapshotIds) { const excerptId = sourceToExcerpt.get(sourceId); if (!excerptId) throw new Error('Candidate support disappeared'); await ctx.db.insert('learnClaimSupports', { userId: args.tokenIdentifier, sessionContentClaimId: claimId, sourceExcerptId: excerptId, sourceSnapshotId: sourceId as Id<'learnSourceSnapshots'>, entailment: 'entailed', verifierVersion: item.verifierVersion, confidence: item.confidence, conflictStatus: 'clear', evidenceStatus: 'evidence_available' }) } }
  await ctx.db.patch(input.session._id, { status: 'ready', revision: input.session.revision + 1 }); await ctx.db.patch(job._id, { status: 'succeeded', revision: job.revision + 1, leaseToken: undefined, leaseExpiresAt: undefined, checkpoint: undefined, terminalReason: undefined, updatedAt: now }); return { status: 'ready' as const, sessionContentId: contentId }
} })

export const executeSessionContentGeneration = internalAction({ args: { tokenIdentifier: v.string(), jobId: v.id('learnJobs'), expectedRevision: v.number() }, handler: async (ctx, args) => { const lease: { kind: 'leased', leaseToken: string, revision: number } | { kind: 'blocked' } = await ctx.runMutation(internal.learnV2SessionContent.leaseSessionContentGeneration, args); if (lease.kind !== 'leased') return { status: 'blocked' }; const begun: { status: 'running' | 'blocked', revision: number } = await ctx.runMutation(internal.learnV2SessionContent.beginSessionContentGeneration, { ...args, leaseToken: lease.leaseToken, expectedRevision: lease.revision }); if (begun.status !== 'running') return begun; return { status: 'running' } } })

export const startStudySession = mutation({ args: { studySessionId: v.id('studySessions'), expectedSessionRevision: v.number(), idempotencyKey: v.string() }, handler: async (ctx, args) => { const userId = await requireLearnV2MutationAccess(ctx); if (!args.idempotencyKey.trim() || args.idempotencyKey.length > 128) throw new Error('Idempotency key is invalid'); const session = await ctx.db.get(args.studySessionId); if (!session || session.userId !== userId) throw new Error('Study session is not ready'); if (session.status === 'in_progress' && session.startedSessionContentId) return { status: 'in_progress' as const, sessionContentId: session.startedSessionContentId, sessionContentRevision: session.startedSessionContentRevision }; if (session.status !== 'ready' || session.revision !== args.expectedSessionRevision) throw new Error('Study session is not ready'); const content = await ctx.db.query('sessionContent').withIndex('by_userId_and_studySessionId_and_revision', q => q.eq('userId', userId).eq('studySessionId', session._id)).order('desc').first(); if (!content || content.status !== 'published') throw new Error('Published session content is required'); await ctx.db.patch(session._id, { status: 'in_progress', revision: session.revision + 1, startedSessionContentId: content._id, startedSessionContentRevision: content.revision }); return { status: 'in_progress' as const, sessionContentId: content._id, sessionContentRevision: content.revision } } })

export const getSessionContent = query({ args: { studySessionId: v.id('studySessions') }, handler: async (ctx, args) => { const userId = await requireLearnV2QueryAccess(ctx); const content = await ctx.db.query('sessionContent').withIndex('by_userId_and_studySessionId_and_revision', q => q.eq('userId', userId).eq('studySessionId', args.studySessionId)).order('desc').first(); if (!content || content.status !== 'published') return null; return content } })
