<script setup lang="ts">
import { useLearnV2Journey } from '~/composables/useLearnV2Journey'
import type { LearnOutcomeDraft } from '~/types/learn-v2-journey'
const route = useRoute(); const router = useRouter(); const { allFolders } = useFolders()
const draftId = computed(() => typeof route.query.draftId === 'string' ? route.query.draftId : null)
const { allowed, checkingAccess, createMission, saveOutcomeDraft, mission, busy, error } = useLearnV2Journey(draftId)
const selectedFolderId = ref(String(route.query.folderId ?? ''))
const selectedFolder = computed(() => allFolders.value?.find(folder => String(folder._id) === selectedFolderId.value) ?? null)
watch(mission, value => { if (value?.learningVoid?.status === 'draft') selectedFolderId.value = String(value.learningVoid.folderId) }, { immediate: true })
const draft = computed<LearnOutcomeDraft>(() => ({ folderName: selectedFolder.value?.name, folderDocumentCount: 0, outcome: mission.value?.currentBlueprint?.desiredOutcome ?? mission.value?.learningVoid?.title ?? '', mode: mission.value?.currentBlueprint?.mode ?? 'understand', depth: mission.value?.currentBlueprint?.desiredDepth ?? 'working', targetDate: mission.value?.currentBlueprint?.targetLocalDate ?? undefined, sessionMinutes: mission.value?.currentBlueprint?.sessionMinutes ?? 25, sourcePolicy: mission.value?.currentBlueprint?.sourcePolicy ?? 'folder_plus_web' }))
async function continueToSources(intent: LearnOutcomeDraft) { if (!selectedFolderId.value) return; const id = await createMission(selectedFolderId.value, intent); await router.push(`/app/learn/${id}?section=sources`) }
async function saveDraft(intent: LearnOutcomeDraft) { if (!selectedFolderId.value) return; const id = await saveOutcomeDraft(selectedFolderId.value, intent); await router.replace({ query: { draftId: id } }) }
</script>
<template><main><section v-if="checkingAccess" class="p-6" aria-live="polite">Checking access…</section><section v-else-if="!allowed" class="p-6">This learning experience is not available for this account.</section><section v-else><div class="mx-auto max-w-5xl px-4 pt-6 sm:px-6"><label class="block max-w-sm text-sm font-medium">Folder<select v-model="selectedFolderId" data-testid="learn-v2-create-folder" class="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2"><option value="" disabled>Choose a folder</option><option v-for="folder in allFolders" :key="folder._id" :value="String(folder._id)">{{ folder.name }}</option></select></label><p v-if="!selectedFolderId" class="mt-2 text-sm text-muted-foreground">Choose the folder whose evidence should ground this learning plan.</p><p v-else-if="draftId" class="mt-2 text-sm text-muted-foreground" data-testid="learn-v2-draft-resumed">Draft resumed. Your outcome and study rhythm are saved to this learning plan.</p><p v-if="error" role="alert" class="mt-3 text-sm text-destructive">{{ error }}</p><p v-if="busy" aria-live="polite" class="mt-3 text-sm text-muted-foreground">Saving your learning workspace…</p></div><LearnV2OutcomeCanvas :draft="draft" @save-draft="saveDraft" @continue-to-sources="continueToSources" /></section></main></template>
