/* eslint-disable @typescript-eslint/no-explicit-any -- Convex generated journey projection is intentionally adapted at this single boundary. */
import { computed, ref, toValue, type MaybeRef } from 'vue'
import { api } from '#convex/api'
import type { LearnHubSnapshot, LearnMissionSnapshot, LearnOutcomeDraft, LearnPlanSnapshot, LearnReadinessItem, LearnSourceSnapshot, LearnObjectiveSnapshot } from '~/types/learn-v2-journey'

type Mission = any
const key = (name: string) => `${name}:${crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`}`
const dateTime = (value?: number | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(value) : 'Not scheduled yet'
const mapStatus = (status: string): LearnMissionSnapshot['lifecycle'] => (({ draft: 'draft', sourcing: 'source_review', source_review: 'source_review', map_review: 'map_review', calibration: 'calibration', plan_review: 'plan_review', scheduled: 'active', active: 'active', needs_attention: 'blocked', failed: 'blocked', paused: 'blocked', archived: 'superseded', completed: 'superseded' } as const)[status as keyof Record<string, LearnMissionSnapshot['lifecycle']>] ?? 'draft')

function nextAction(row: any) {
  const actions: Record<string, LearnMissionSnapshot['nextAction']> = {
    source_selection: { kind: 'finish_setup', label: 'Continue source setup', detail: 'Choose the evidence that can support this learning plan.' },
    source_review: { kind: 'review_sources', label: 'Review sources', detail: 'Accept evidence before generating your learning map.' },
    blueprint_generation: { kind: 'review_sources', label: 'Generate learning map', detail: 'Your accepted evidence is ready to shape into capabilities.' },
    map_review: { kind: 'review_map', label: 'Review learning map', detail: 'Confirm the capabilities and prerequisites before calibration.' },
    calibration: { kind: 'calibrate', label: 'Calibrate your starting point', detail: 'A short cold attempt tailors the schedule; it does not award mastery.' },
    plan_preview: { kind: 'review_plan', label: 'Build plan preview', detail: 'Check feasibility, buffers, and your first sessions.' },
    plan_acceptance: { kind: 'review_plan', label: 'Review plan', detail: 'Accept an in-app plan before sessions are scheduled.' },
    mastery: { kind: 'resume_session', label: 'Resume session', detail: 'Finish your current deliberate-practice session.' },
    study_session: { kind: 'start_session', label: 'Start next session', detail: 'Your next evidence-grounded practice is ready.' },
  }
  return actions[row.nextAction] ?? { kind: 'resolve_block', label: 'Review learning plan', detail: 'This plan needs attention before it can continue.' }
}

function missionSnapshot(row: any): LearnMissionSnapshot {
  const mastery = row.mastery ?? []
  const states = mastery.map((item: any) => item.record?.state ?? 'unseen')
  return { id: String(row.learningVoid?._id ?? row._id), title: row.learningVoid?.title ?? row.title ?? 'Learning plan', folderName: row.folder?.name ?? 'Folder', lifecycle: mapStatus(row.learningVoid?.status ?? row.status ?? 'draft'), nextAction: nextAction(row), mastery: { retained: states.filter((state: string) => state === 'retained').length, independent: states.filter((state: string) => state === 'independent').length, learning: states.filter((state: string) => ['learning', 'guided', 'provisionally_known'].includes(state)).length, needsReview: states.filter((state: string) => state === 'needs_review').length, total: Math.max(states.length, row.map?.objectives?.length ?? 0) }, upcomingLabel: row.plan?.sessions?.[0] ? `Next: ${dateTime(row.plan.sessions[0].scheduledStartAt)}` : undefined }
}

export function useLearnV2Journey(learningVoidId?: MaybeRef<string | null | undefined>) {
  const { allowed, checkingAccess } = useLearnV2Access()
  const id = computed(() => toValue(learningVoidId) ?? null)
  const hubQuery = import.meta.client ? useConvexQuery(api.learnV2Journey.listHub, {}, { enabled: allowed }) : { data: ref<any>(null), pending: ref(false) }
  const missionQuery = import.meta.client ? useConvexQuery(api.learnV2Journey.getMission, computed(() => ({ learningVoidId: id.value as never })), { enabled: computed(() => allowed.value && !!id.value) }) : { data: ref<Mission | null>(null), pending: ref(false) }
  const createVoid = import.meta.client ? useConvexMutation(api.learnV2Lifecycle.createLearningVoid) : { mutate: async () => null }
  const createBlueprint = import.meta.client ? useConvexMutation(api.learnV2Lifecycle.createBlueprintDraft) : { mutate: async () => null }
  const transitionVoid = import.meta.client ? useConvexMutation(api.learnV2Lifecycle.transitionLearningVoid) : { mutate: async () => null }
  const transitionBlueprint = import.meta.client ? useConvexMutation(api.learnV2Lifecycle.transitionBlueprintRevision) : { mutate: async () => null }
  const freezeManifest = import.meta.client ? useConvexMutation(api.learnV2FolderManifests.freezeManifest) : { mutate: async () => null }
  const configureIntent = import.meta.client ? useConvexMutation(api.learnV2Blueprints.configureBlueprintIntent) : { mutate: async () => null }
  const startGeneration = import.meta.client ? useConvexMutation(api.learnV2Blueprints.startBlueprintGeneration) : { mutate: async () => null }
  const acceptSourceMutation = import.meta.client ? useConvexMutation(api.learnV2Sources.acceptSource) : { mutate: async () => null }
  const rejectSourceMutation = import.meta.client ? useConvexMutation(api.learnV2Sources.rejectSource) : { mutate: async () => null }
  const acceptMap = import.meta.client ? useConvexMutation(api.learnV2MapCalibration.acceptBlueprintMap) : { mutate: async () => null }
  const submitCalibration = import.meta.client ? useConvexAction(api.learnV2MapCalibration.submitCalibrationAttempt) : { mutate: async () => null }
  const completeCalibrationMutation = import.meta.client ? useConvexMutation(api.learnV2MapCalibration.completeCalibration) : { mutate: async () => null }
  const createPreviewMutation = import.meta.client ? useConvexMutation(api.learnV2Plans.createPlanPreview) : { mutate: async () => null }
  const acceptPreviewMutation = import.meta.client ? useConvexMutation(api.learnV2Plans.acceptPlanPreview) : { mutate: async () => null }
  const error = ref<string | null>(null)
  const busy = ref(false)
  const mission = computed(() => missionQuery.data.value as Mission | null | undefined)
  const hub = computed<LearnHubSnapshot>(() => {
    const rows = (hubQuery.data.value as any)?.items ?? []
    const missions = rows.map((row: any) => missionSnapshot(row))
    return { missions, today: missions.find((item: LearnMissionSnapshot) => ['start_session', 'resume_session', 'review_now'].includes(item.nextAction.kind)) ?? missions[0] ?? null }
  })
  const snapshot = computed(() => mission.value ? missionSnapshot(mission.value) : null)
  const sources = computed<LearnSourceSnapshot[]>(() => (mission.value?.sources?.items ?? []).map((row: any) => ({ id: String(row._id), title: row.publicLocator ?? 'Evidence source', origin: 'folder_document', publisher: row.publicLocator ? new URL(row.publicLocator).hostname : undefined, retrievedLabel: row.status.replaceAll('_', ' '), coverage: row.effectiveStatus === 'unavailable' ? 'gap' : row.effectiveStatus === 'user_accepted' ? 'strong' : 'partial', lifecycle: row.effectiveStatus, objectives: [] })))
  const objectives = computed<LearnObjectiveSnapshot[]>(() => (mission.value?.map?.objectives ?? []).map((row: any) => ({ id: String(row._id), title: row.title, capability: row.capability, milestone: mission.value?.map?.milestones?.find((milestone: any) => String(milestone._id) === String(row.milestoneId))?.title ?? 'Capability', effortMinutes: row.estimatedMinutes, mastery: mission.value?.mastery?.find((entry: any) => String(entry.objectiveId) === String(row._id))?.record?.state ?? 'unseen', coverage: row.coverage ?? 'gap', prerequisiteIds: row.prerequisiteObjectiveIds?.map(String), assessment: row.assessmentContract?.instructions })))
  const readiness = computed<LearnReadinessItem[]>(() => { const row = mission.value; if (!row) return []; const status = row.learningVoid.status; return [{ id: 'outcome', label: 'Outcome', state: row.currentBlueprint?.desiredOutcome ? 'complete' : 'current' }, { id: 'sources', label: 'Sources', state: row.sources.counts.accepted ? 'complete' : status === 'source_review' || status === 'sourcing' ? 'current' : 'locked', detail: row.sources.counts.accepted ? `${row.sources.counts.accepted} accepted` : 'Accept evidence' }, { id: 'map', label: 'Learning map', state: row.map?.objectives?.length ? 'complete' : status === 'map_review' ? 'current' : 'locked' }, { id: 'plan', label: 'Study plan', state: row.plan?.accepted ? 'complete' : status === 'plan_review' ? 'current' : 'locked' }] })
  const plan = computed<LearnPlanSnapshot | null>(() => { const row = mission.value; const revision = row?.plan?.preview ?? row?.plan?.accepted; if (!row || !revision) return null; const result = JSON.parse(revision.resultSnapshot ?? '{}'); return { feasibility: revision.feasibility ?? 'pending', headline: result.status === 'feasible' ? 'Your plan is feasible' : 'Your plan needs an adjustment', detail: result.reasonCodes?.join(', ') || 'Review the timeline before accepting.', weeklyLoadLabel: 'Based on your availability', targetLabel: revision.timezone, sessions: (row.plan.sessions ?? []).map((session: any) => ({ id: String(session._id), title: objectives.value.find(objective => objective.id === String(session.primaryObjectiveId))?.title ?? 'Study session', when: dateTime(session.scheduledStartAt), durationMinutes: Math.max(1, Math.round((session.scheduledEndAt - session.scheduledStartAt) / 60_000)), kind: session.placementKind ?? 'learning', objectiveId: String(session.primaryObjectiveId) })), alternatives: result.alternatives?.map((item: any) => item.code) } })
  async function run(work: () => Promise<any>) { busy.value = true; error.value = null; try { return await work() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not update this learning plan. Please try again.'; throw cause } finally { busy.value = false } }
  async function createMission(folderId: string, draft: LearnOutcomeDraft) { return await run(async () => { const created: any = await createVoid.mutate({ folderId: folderId as never, title: draft.outcome, idempotencyKey: key('create-void') }); const blueprint: any = await createBlueprint.mutate({ learningVoidId: created.learningVoidId, expectedVoidRevision: created.revision, idempotencyKey: key('create-blueprint') }); const sourcing: any = await transitionVoid.mutate({ learningVoidId: created.learningVoidId, status: 'sourcing', expectedRevision: created.revision + 1, idempotencyKey: key('start-sourcing') }); const sourceReview: any = await transitionVoid.mutate({ learningVoidId: created.learningVoidId, status: 'source_review', expectedRevision: sourcing.revision, idempotencyKey: key('open-source-review') }); const sourceBlueprint: any = await transitionBlueprint.mutate({ blueprintRevisionId: blueprint.blueprintRevisionId, status: 'source_review', expectedRecordRevision: blueprint.blueprintRecordRevision, idempotencyKey: key('open-blueprint-source-review') }); await freezeManifest.mutate({ learningVoidId: created.learningVoidId, blueprintRevisionId: blueprint.blueprintRevisionId, expectedVoidRevision: sourceReview.revision, expectedBlueprintRecordRevision: sourceBlueprint.blueprintRecordRevision, folderIds: (draft.sourcePolicy === 'web_only' ? [] : [folderId]) as never, documentIds: [], idempotencyKey: key('freeze-folder-sources') }); return String(created.learningVoidId) }) }
  async function configureAndGenerate(draft: LearnOutcomeDraft) { const row = mission.value; if (!row?.currentBlueprint) return; return await run(async () => { const configured: any = await configureIntent.mutate({ blueprintRevisionId: row.currentBlueprint._id, expectedBlueprintRecordRevision: row.currentBlueprint.recordRevision, desiredOutcome: draft.outcome, mode: draft.mode, desiredDepth: draft.depth, sourcePolicy: draft.sourcePolicy, idempotencyKey: key('configure-intent') }); return await startGeneration.mutate({ learningVoidId: row.learningVoid._id, blueprintRevisionId: row.currentBlueprint._id, expectedVoidRevision: row.learningVoid.revision, expectedBlueprintRecordRevision: configured.recordRevision, idempotencyKey: key('generate-map') }) }) }
  async function acceptSource(source: LearnSourceSnapshot) { return await run(() => acceptSourceMutation.mutate({ sourceSnapshotId: source.id as never, expectedRevision: (mission.value?.sources.items.find((item: any) => String(item._id) === source.id)?.recordRevision ?? 1), idempotencyKey: key('accept-source') })) }
  async function rejectSource(source: LearnSourceSnapshot) { return await run(() => rejectSourceMutation.mutate({ sourceSnapshotId: source.id as never, expectedRevision: (mission.value?.sources.items.find((item: any) => String(item._id) === source.id)?.recordRevision ?? 1), idempotencyKey: key('reject-source') })) }
  async function acceptLearningMap() { const row = mission.value; if (!row?.currentBlueprint) return; return await run(() => acceptMap.mutate({ blueprintRevisionId: row.currentBlueprint._id, expectedRecordRevision: row.currentBlueprint.recordRevision, expectedVoidRevision: row.learningVoid.revision, idempotencyKey: key('accept-map') })) }
  async function submitCalibrationAttempt(objectiveId: string, response: string, confidence: number) { const row = mission.value; if (!row?.currentBlueprint) return; return await run(() => submitCalibration.mutate({ blueprintRevisionId: row.currentBlueprint._id, objectiveId: objectiveId as never, expectedBlueprintRecordRevision: row.currentBlueprint.recordRevision, expectedVoidRevision: row.learningVoid.revision, response, confidence, usedHint: false, usedReveal: false, idempotencyKey: key('calibration') })) }
  async function completeCalibration() { const row = mission.value; if (!row?.currentBlueprint) return; return await run(() => completeCalibrationMutation.mutate({ blueprintRevisionId: row.currentBlueprint._id, expectedBlueprintRecordRevision: row.currentBlueprint.recordRevision, expectedVoidRevision: row.learningVoid.revision, idempotencyKey: key('complete-calibration') })) }
  function defaultSchedule() { const now = new Date(); const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC'; return { version: 'learn-v2.schedule-input.v1' as const, timezone, startLocalDate: now.toISOString().slice(0, 10), targetLocalDate: null, sessionMinutes: 25, availability: [{ weekday: 1, start: '18:00', end: '20:00' }, { weekday: 3, start: '18:00', end: '20:00' }, { weekday: 6, start: '10:00', end: '12:00' }], blackoutDates: [], reviewIntervalsDays: [1, 3], minRestMinutes: 720 } }
  async function createPlanPreview() { const row = mission.value; if (!row?.currentBlueprint) return; return await run(() => createPreviewMutation.mutate({ learningVoidId: row.learningVoid._id, blueprintRevisionId: row.currentBlueprint._id, expectedVoidRevision: row.learningVoid.revision, expectedBlueprintRecordRevision: row.currentBlueprint.recordRevision, idempotencyKey: key('plan-preview'), schedulingInput: defaultSchedule() })) }
  async function acceptPlan() { const row = mission.value; const preview = row?.plan?.preview; if (!row || !preview) return; return await run(() => acceptPreviewMutation.mutate({ studyPlanRevisionId: preview._id, expectedVoidRevision: row.learningVoid.revision, expectedPlanRecordRevision: preview.recordRevision, idempotencyKey: key('accept-plan') })) }
  return { allowed, checkingAccess, hub, mission, snapshot, sources, objectives, readiness, plan, busy, error, createMission, configureAndGenerate, acceptSource, rejectSource, acceptLearningMap, submitCalibrationAttempt, completeCalibration, createPlanPreview, acceptPlan }
}
