<script setup lang="ts">
import { api } from '#convex/api'
const route = useRoute(); const id = String(route.params.sessionId); const voidId = String(route.params.learningVoidId); const router = useRouter(); const { allowed, checkingAccess } = useLearnV2Access()
const candidateQuery = import.meta.client ? useConvexQuery(api.learnV2Journey.getSessionCandidate, { learningVoidId: voidId as never, studySessionId: id as never }, { enabled: allowed }) : { data: ref(null) }
const candidate = computed(() => candidateQuery.data.value as { status: string, studySessionId: string, sessionRevision: number, scheduledStartAt: number, scheduledEndAt: number, timezone: string, objective: { title: string, capability: string, estimatedMinutes: number | null }, plan: { recordRevision: number }, blueprint: { recordRevision: number }, content: { revision: number } | null } | null)
const candidatePending = computed(() => 'pending' in candidateQuery && Boolean(candidateQuery.pending.value))
const sessionActive = ref(false)
watch(() => candidate.value?.status, (status) => {
  if (status === 'in_progress') sessionActive.value = true
}, { immediate: true })
function leaveSession() { void router.replace(`/app/learn/${voidId}?section=plan`) }
</script>
<template><main class="min-h-full" data-testid="learn-v2-session-page"><section v-if="checkingAccess" class="mx-auto max-w-2xl p-6" aria-live="polite">Checking learning access…</section><section v-else-if="!allowed" class="mx-auto max-w-2xl p-6">This learning experience is not available for this account.</section><section v-else-if="candidatePending" class="mx-auto max-w-2xl p-6" aria-live="polite">Preparing your focused session…</section><section v-else-if="!candidate" class="mx-auto max-w-2xl p-6">This study session is unavailable.</section><section v-else-if="candidate.status === 'planned' || !candidate.content" class="mx-auto max-w-2xl p-6" aria-live="polite">This session is scheduled and its study material is still being prepared.</section><section v-else-if="!sessionActive && !['ready', 'in_progress'].includes(candidate.status)" class="mx-auto max-w-2xl p-6" aria-live="polite">This session is no longer available to start. Open Today to continue with your current learning plan.</section><LearnV2TodaySession v-else :candidate="{ studySessionId: candidate.studySessionId, sessionRevision: candidate.sessionRevision, contentRevision: candidate.content.revision, planRecordRevision: candidate.plan.recordRevision, blueprintRecordRevision: candidate.blueprint.recordRevision, objectiveTitle: candidate.objective.title, capability: candidate.objective.capability, estimatedMinutes: candidate.objective.estimatedMinutes ?? 25, scheduledStartAt: candidate.scheduledStartAt, scheduledEndAt: candidate.scheduledEndAt, timezone: candidate.timezone, reason: 'workspace', progress: { retained: 0, independent: 0, total: 0 }, initiallyStarted: candidate.status === 'in_progress' }" @leave="leaveSession" /></main></template>
