export const OUTCOME_REGISTRY_VERSION = 'outcome_metrics.v1'
export const OUTCOME_QUERY_VERSION = 'outcome_fixture_query.v1'
export const OUTCOME_FIXTURE_VERSION = 'adaptive_learn_outcome_fixture.v1'
export const OUTCOME_FIXTURE_LIMITS = Object.freeze({ bytes: 262_144, rows: 1000, windowMs: 90 * 86400000 })
export const OUTCOME_SOURCE_VERSIONS = Object.freeze({ retention: 'capability_attempt_fixture.v1', experiment: 'experiment_outcome_fixture.v1', crossFeature: 'contribution_lineage_fixture.v1', accessibility: 'accessibility_task_fixture.v1', cost: 'recorded_request_cost_fixture.v1', support: 'support_contact_fixture.v1', supportDenominator: 'support_denominator_fixture.v1' })

const common = {
  queryIdentity: OUTCOME_QUERY_VERSION, fixtureIdentity: 'outcomes.v1',
  timeWindow: 'fixture [windowStart, windowEnd], at most 90 days; retention uses local calendar dates',
  ownerPrincipal: null, approval: 'pending', liveTelemetryAdapter: 'pending',
} as const

export const OUTCOME_METRIC_DEFINITIONS = Object.freeze([
  Object.freeze({ ...common, version: 'delayed_retention.v1', eventSource: 'capability_attempt_fixture.v1 (synthetic only)', eligibility: 'independently enumerated capabilities with pinned unassisted first independent pass; due at seven local calendar days', numerator: 'due capabilities whose earliest eligible delayed unassisted check scores >=80; ties by immutable attempt identity', denominator: 'all due capabilities; observed-check subaggregate reports only checked capabilities', exclusions: Object.freeze(['not_due', 'early', 'assisted', 'missing_check', 'missing_source']), ownerRole: 'product_analytics' }),
  ...[
    ['experiment_performance.v1', 'earliest authoritative outcome attempt per eligible authenticated learner assignment passes representative task'],
    ['experiment_completion.v1', 'earliest authoritative outcome attempt per eligible authenticated learner assignment completes'],
    ['experiment_usefulness.v1', 'self-reported rating >=4 of 5 for earliest authoritative outcome per eligible assignment; missing rating unknown'],
  ].map(([version, numerator]) => Object.freeze({ ...common, version, eventSource: OUTCOME_SOURCE_VERSIONS.experiment, eligibility: 'immutable analysis plan digest, authenticated learner assignment unit, cohort and source pins; report arms separately', numerator, denominator: 'unique eligible assignments per arm; outcome attempts counted separately without duplication', exclusions: Object.freeze(['flag_ineligible', 'not_authenticated', 'missing_outcome', 'missing_rating', 'missing_source']), ownerRole: 'product_analytics' })),
  Object.freeze({ ...common, version: 'cross_feature_improvement.v1', eventSource: OUTCOME_SOURCE_VERSIONS.crossFeature, eligibility: 'canonical immutable contribution revision and provenance key; synthetic producer-verified lineage joined to authoritative attempt; all five origin types retained', numerator: 'unique authoritative attempts with recorded next-action improvement', denominator: 'unique authoritative attempts referenced by eligible contributions', exclusions: Object.freeze(['identical_retry', 'duplicate_attempt_projection', 'missing_outcome', 'missing_source', 'conflicting_or_unverified_provenance_rejected']), ownerRole: 'data_engineering' }),
  ...['accessibility_completion.v1', 'recovery_success.v1'].map(version => Object.freeze({ ...common, version, eventSource: OUTCOME_SOURCE_VERSIONS.accessibility, eligibility: 'eligible task opportunities pinned to protocol, tested SHA, task/baseline/treatment versions, evidence digest and synthetic verifier; arms separate', numerator: version === 'accessibility_completion.v1' ? 'verified completed tasks' : 'verified recovered tasks', denominator: 'unique eligible task opportunities per arm including missing outcome proof', exclusions: Object.freeze(['not_applicable', 'missing_verified_outcome', 'missing_source']), ownerRole: 'qa' })),
  Object.freeze({ ...common, version: 'actual_cost_per_request.v1', eventSource: OUTCOME_SOURCE_VERSIONS.cost, eligibility: 'complete eligible request enumeration, recorded dispatch state and integer actual USD micros; no configured ceiling or reservation substitution', numerator: 'sum actually recorded cost in USD micros; incomplete sums explicitly observed only', denominator: 'unique eligible dispatched requests; unknown dispatch or missing actual cost makes complete result unknown', exclusions: Object.freeze(['ineligible', 'not_dispatched', 'unknown_dispatch', 'missing_actual_cost', 'missing_source']), ownerRole: 'platform_operations' }),
  Object.freeze({ ...common, version: 'support_contacts.v1', eventSource: 'support_contact_fixture.v1 + support_denominator_fixture.v1 (synthetic only; no live closed-taxonomy event exists)', eligibility: 'explicitly eligible contacts with opaque identity, cohort, occurredAt and category; no contact text', numerator: 'unique eligible contact identities by cohort, category counts separate', denominator: 'explicit source-covered eligible learner population per cohort; contacts per eligible learner is a frequency, not a success probability', exclusions: Object.freeze(['ineligible', 'identical_retry', 'missing_contact_source', 'missing_denominator_source']), ownerRole: 'support_operations' }),
])
