<script setup lang="ts">
import { ArrowRight, BookCheck, CircleAlert } from '@lucide/vue'
import type { LearnMasteryState, LearnObjectiveSnapshot } from '~/types/learn-v2-journey'
const { objectives } = defineProps<{ objectives: LearnObjectiveSnapshot[] }>()
const emit = defineEmits<{ openObjective: [objectiveId: string]; startReview: [objectiveId: string] }>()
const groups: Array<{ state: LearnMasteryState; label: string }> = [{ state: 'retained', label: 'Retained' }, { state: 'independent', label: 'Independent' }, { state: 'learning', label: 'Learning' }, { state: 'needs_review', label: 'Needs review' }, { state: 'blocked', label: 'Blocked' }]
</script>
<template>
  <section data-testid="learn-v2-capability-shelf"><header><p class="font-inter text-xs uppercase tracking-wide text-primary">Capability progress</p><h2 class="mt-1 font-dm-sans text-xl font-bold">What you have demonstrated</h2><p class="mt-1 text-sm text-muted-foreground">Progress reflects evidence from attempts, not pages opened or lessons completed.</p></header><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><section v-for="group in groups" v-show="objectives.some(item => item.mastery === group.state)" :key="group.state" class="rounded-xl border border-border bg-card p-4"><h3 class="flex items-center gap-2 font-dm-sans text-base font-semibold"><BookCheck v-if="group.state === 'retained' || group.state === 'independent'" class="h-4 w-4 text-emerald-300" /><CircleAlert v-else-if="group.state === 'needs_review' || group.state === 'blocked'" class="h-4 w-4 text-amber-300" /><span v-else class="h-2 w-2 rounded-full bg-primary" />{{ group.label }}</h3><ul class="mt-3 space-y-2"><li v-for="objective in objectives.filter(item => item.mastery === group.state)" :key="objective.id" class="rounded-lg bg-background/50 px-3 py-2"><button type="button" class="w-full text-left text-sm font-medium hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" @click="emit('openObjective', objective.id)">{{ objective.title }}</button><div v-if="group.state === 'needs_review'" class="mt-2"><UiButton size="sm" @click="emit('startReview', objective.id)">Review now <ArrowRight class="ml-1 h-3.5 w-3.5" /></UiButton></div></li></ul></section></div></section>
</template>
