<script setup lang="ts">
import { Check, CircleAlert, CircleDot, LockKeyhole } from '@lucide/vue'
import type { LearnMissionSnapshot, LearnReadinessItem, LearnWorkspaceSection } from '~/types/learn-v2-journey'
const { mission, activeSection, readiness } = defineProps<{ mission: LearnMissionSnapshot; activeSection: LearnWorkspaceSection; readiness: LearnReadinessItem[] }>()
const emit = defineEmits<{ navigate: [section: LearnWorkspaceSection]; act: [missionId: string] }>()
const sections: Array<{ id: LearnWorkspaceSection; label: string }> = [{ id: 'overview', label: 'Overview' }, { id: 'sources', label: 'Sources' }, { id: 'map', label: 'Learning map' }, { id: 'plan', label: 'Plan' }, { id: 'progress', label: 'Progress' }]
const stateIcon = { complete: Check, current: CircleDot, attention: CircleAlert, locked: LockKeyhole }
</script>
<template>
  <section class="mx-auto w-full max-w-7xl px-4 py-5 sm:px-6" data-testid="learn-v2-workspace"><header class="border-b border-border pb-5"><p class="font-inter text-xs uppercase tracking-wide text-muted-foreground">{{ mission.folderName }}</p><div class="mt-1 flex flex-wrap items-center justify-between gap-4"><div><h1 class="font-dm-sans text-2xl font-bold tracking-tight">{{ mission.title }}</h1><p class="mt-1 text-sm text-muted-foreground">{{ mission.nextAction.detail }}</p></div><UiBadge variant="secondary" class="capitalize">{{ mission.lifecycle.replace('_', ' ') }}</UiBadge></div><nav class="-mb-5 mt-5 flex gap-1 overflow-x-auto" aria-label="Learning workspace"><button v-for="section in sections" :key="section.id" :data-testid="`learn-v2-workspace-nav-${section.id}`" :aria-current="activeSection === section.id ? 'page' : undefined" type="button" class="shrink-0 border-b-2 border-transparent px-3 py-3 text-sm text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring aria-[current=page]:border-primary aria-[current=page]:text-foreground" @click="emit('navigate', section.id)">{{ section.label }}</button></nav></header><div class="grid gap-6 py-6 lg:grid-cols-[minmax(0,1fr)_18rem]"><main class="min-w-0"><slot /></main><aside class="space-y-4"><UiCard class="gap-3 p-4"><h2 class="font-dm-sans text-base font-semibold">Keep moving</h2><UiButton data-testid="learn-v2-workspace-next-action" class="w-full justify-between" @click="emit('act', mission.id)">{{ mission.nextAction.label }}<span aria-hidden="true">→</span></UiButton></UiCard><UiCard class="gap-3 p-4"><h2 class="font-dm-sans text-base font-semibold">Readiness</h2><ul class="space-y-3"><li v-for="item in readiness" :key="item.id" class="flex gap-2 text-sm"><component :is="stateIcon[item.state]" class="mt-0.5 h-4 w-4 shrink-0" :class="item.state === 'attention' ? 'text-amber-400' : item.state === 'complete' ? 'text-emerald-300' : 'text-muted-foreground'" /><span><span class="block">{{ item.label }}</span><span v-if="item.detail" class="block text-xs text-muted-foreground">{{ item.detail }}</span></span></li></ul></UiCard></aside></div></section>
</template>
