<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import type { LearnScheduleInput } from '~/types/learn-v2-journey'

const { input, submitLabel = 'Build plan preview', busy = false } = defineProps<{ input: LearnScheduleInput; submitLabel?: string; busy?: boolean }>()
const emit = defineEmits<{ submit: [input: LearnScheduleInput]; cancel: [] }>()
const form = reactive<LearnScheduleInput>({ ...input, availability: input.availability.map(item => ({ ...item })), blackoutDates: [...input.blackoutDates], reviewIntervalsDays: [...input.reviewIntervalsDays] })
watch(() => input, value => Object.assign(form, { ...value, availability: value.availability.map(item => ({ ...item })), blackoutDates: [...value.blackoutDates], reviewIntervalsDays: [...value.reviewIntervalsDays] }), { deep: true })
const days = [{ weekday: 1, label: 'Mon' }, { weekday: 2, label: 'Tue' }, { weekday: 3, label: 'Wed' }, { weekday: 4, label: 'Thu' }, { weekday: 5, label: 'Fri' }, { weekday: 6, label: 'Sat' }, { weekday: 7, label: 'Sun' }]
const selectedDays = computed(() => new Set(form.availability.map(item => item.weekday)))
function toggleDay(weekday: number) { const index = form.availability.findIndex(item => item.weekday === weekday); if (index >= 0) form.availability.splice(index, 1); else form.availability.push({ weekday, start: '18:00', end: '20:00' }); form.availability.sort((a, b) => a.weekday - b.weekday) }
function submit() { emit('submit', { ...form, targetLocalDate: form.targetLocalDate || null, availability: form.availability.map(item => ({ ...item })), blackoutDates: [...form.blackoutDates], reviewIntervalsDays: [...form.reviewIntervalsDays] }) }
</script>

<template>
  <form class="rounded-xl border border-border bg-card p-5" data-testid="learn-v2-schedule-editor" @submit.prevent="submit">
    <div class="flex items-start justify-between gap-4"><div><p class="font-inter text-xs uppercase tracking-wide text-primary">Study rhythm</p><h2 class="mt-1 font-dm-sans text-xl font-bold">Make the plan fit your week</h2><p class="mt-1 text-sm text-muted-foreground">Budds checks the actual local times and target date before you accept anything.</p></div></div>
    <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label class="text-sm font-medium">Time zone<input v-model="form.timezone" data-testid="learn-v2-schedule-timezone" required class="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2" aria-describedby="learn-v2-timezone-help"><span id="learn-v2-timezone-help" class="mt-1 block text-xs font-normal text-muted-foreground">Use an IANA name, e.g. America/Toronto.</span></label><label class="text-sm font-medium">Start date<input v-model="form.startLocalDate" data-testid="learn-v2-schedule-start" type="date" required class="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2"></label><label class="text-sm font-medium">Target date<input v-model="form.targetLocalDate" data-testid="learn-v2-schedule-target" type="date" :min="form.startLocalDate" class="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2"></label><label class="text-sm font-medium">Session length<select v-model.number="form.sessionMinutes" data-testid="learn-v2-schedule-minutes" class="mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2"><option v-for="minutes in [15, 20, 25, 30, 45, 60]" :key="minutes" :value="minutes">{{ minutes }} minutes</option></select></label></div>
    <fieldset class="mt-6"><legend class="text-sm font-medium">Weekly availability</legend><p class="mt-1 text-xs text-muted-foreground">Select the days you can study, then set their local time window.</p><div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div v-for="day in days" :key="day.weekday" class="rounded-lg border border-border p-3"><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" :data-testid="`learn-v2-schedule-day-${day.weekday}`" :checked="selectedDays.has(day.weekday)" @change="toggleDay(day.weekday)">{{ day.label }}</label><div v-if="selectedDays.has(day.weekday)" class="mt-3 grid grid-cols-2 gap-2"><input v-model="form.availability.find(item => item.weekday === day.weekday)!.start" type="time" :data-testid="`learn-v2-schedule-window-start-${day.weekday}`" :aria-label="`${day.label} start`" class="rounded border border-input bg-background px-2 py-1.5 text-sm"><input v-model="form.availability.find(item => item.weekday === day.weekday)!.end" type="time" :data-testid="`learn-v2-schedule-window-end-${day.weekday}`" :aria-label="`${day.label} end`" class="rounded border border-input bg-background px-2 py-1.5 text-sm"></div></div></div></fieldset>
    <div class="mt-6 flex flex-wrap justify-end gap-2"><UiButton type="button" variant="ghost" @click="emit('cancel')">Cancel</UiButton><UiButton type="submit" data-testid="learn-v2-create-plan-preview" :disabled="busy || form.availability.length === 0">{{ submitLabel }}</UiButton></div>
  </form>
</template>
