<script setup lang="ts">
const route = useRoute(); const router = useRouter(); const id = computed(() => String(route.params.learningVoidId)); const journey = useLearnV2Journey(id); const response = ref(''); const confidence = ref(3)
const attemptedIds = computed(() => new Set((journey.mission.value?.calibration?.attempts ?? []).map((attempt: { objectiveId: unknown }) => String(attempt.objectiveId))))
const attemptCount = computed(() => attemptedIds.value.size)
const objective = computed(() => journey.objectives.value.find(item => !attemptedIds.value.has(item.id)) ?? null)
const canFinish = computed(() => attemptCount.value >= 3 && attemptCount.value <= 7)
async function submit() { if (!objective.value || !response.value.trim() || attemptCount.value >= 7) return; await journey.submitCalibrationAttempt(objective.value.id, response.value, confidence.value); response.value = '' }
async function finish() { if (!canFinish.value) return; await journey.completeCalibration(); await router.push(`/app/learn/${id.value}?section=plan`) }
</script>
<template><main class="mx-auto max-w-2xl px-4 py-8" data-testid="learn-v2-calibration"><NuxtLink :to="`/app/learn/${id}`" class="text-sm text-muted-foreground hover:text-foreground">← Back to workspace</NuxtLink><section v-if="!journey.mission" class="mt-6" aria-live="polite">Preparing calibration…</section><section v-else class="mt-6"><p class="font-inter text-xs uppercase tracking-wide text-primary">Calibration</p><h1 class="mt-1 font-dm-sans text-2xl font-bold">Find your starting point</h1><p class="mt-2 text-sm text-muted-foreground">Cold attempts tailor the plan. They cannot award retained mastery.</p><UiCard v-if="objective" class="mt-6 p-5"><p class="text-sm text-muted-foreground">{{ attemptCount }} of 3–7 unique capabilities completed</p><h2 class="mt-2 font-dm-sans text-lg font-semibold">{{ objective.capability }}</h2><textarea v-model="response" data-testid="learn-v2-calibration-response" rows="6" class="mt-4 w-full rounded-lg border border-input bg-background p-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="Write your best answer before seeing any teaching…" /><label class="mt-4 block text-sm">How confident are you? <select v-model.number="confidence" class="ml-2 rounded border border-input bg-background px-2 py-1"><option v-for="value in 5" :key="value" :value="value">{{ value }} / 5</option></select></label><UiButton class="mt-5" data-testid="learn-v2-calibration-submit" :disabled="!response.trim() || journey.busy" @click="submit">Submit cold attempt</UiButton></UiCard><UiCard v-else class="mt-6 p-5"><h2 class="font-dm-sans text-lg font-semibold">Ready to build your plan?</h2><p class="mt-2 text-sm text-muted-foreground">{{ canFinish ? 'Your calibration is ready to inform the plan.' : 'Complete at least three unique calibration attempts before continuing.' }}</p><UiButton class="mt-4" data-testid="learn-v2-calibration-complete" :disabled="journey.busy || !canFinish" @click="finish">Build plan preview</UiButton></UiCard><p v-if="journey.error" role="alert" class="mt-4 text-sm text-destructive">{{ journey.error }}</p></section></main></template>
